# Generated by Django 5.1 on 2026-04-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_recibida', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizada', models.DateTimeField(auto_now=True)),
                ('procesado', models.BooleanField(default=False)),
                ('resultado_procesamiento', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TikTok URL',
                'verbose_name_plural': 'TikTok URLs',
                'ordering': ['-fecha_recibida'],
            },
        ),
    ]
